version: "3"
services:
    web:
        build: .
        ports:
            - "3000:3000"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
            - "1435:1433"
        environment:
            SA_PASSWORD: "Pass@123"
            ACCEPT_EULA: "Y"