CREATE DATABASE QL_NHATHUOCTY
GO

USE QL_NHATHUOCTY
GO

--DROP DATABASE QL_NHATHUOCTY

CREATE TABLE THUOC
(
    MATHUOC VARCHAR(10) NOT NULL,
    TENTHUOC NVARCHAR(30),
    MANHOM VARCHAR(5),
    LOAISD NVARCHAR(10),
    THANHPHAN NVARCHAR(40),
    MANCC VARCHAR(10),
    GIASI MONEY,
    GIALE MONEY,
    GIANHAP MONEY,
    DANGBAOCHE NVARCHAR(20),
    QCDONGGOI VARCHAR(10),
    CONGDUNG NVARCHAR(100),
    PRIMARY KEY(MATHUOC)
)

CREATE TABLE NHOMTHUOC
(
    MANHOM VARCHAR(5) NOT NULL,
    TENNHOM NVARCHAR(20),
    SOLUONG INT,
    PRIMARY KEY(MANHOM)
)

CREATE TABLE NHACUNGCAP
(
    MANCC VARCHAR(10) NOT NULL,
    TENNCC NVARCHAR(50),
    DIACHI NVARCHAR(80),
    DIENTHOAI NCHAR(11),
    CONGNO MONEY,
    PRIMARY KEY(MANCC)
)

CREATE TABLE NHANVIEN
(
    MANV VARCHAR(10) NOT NULL,
    TENNV NVARCHAR(50),
    NGAYSINH DATE,
    VANBANG NVARCHAR(30),
    DIACHI NVARCHAR(80),
    PHAI NVARCHAR(3),
    VITRI NVARCHAR(15),
    BOPHAN NVARCHAR(15),
    PRIMARY KEY(MANV)
)

CREATE TABLE KHACHHANG
(
    MAKH VARCHAR(10) NOT NULL,
    TENKHACH NVARCHAR(30),
    DIACHI NVARCHAR(80),
    DIENTHOAI NCHAR(11),
    LOAIKH NVARCHAR(15),
    CONGNO MONEY,
    PRIMARY KEY(MAKH)
)

CREATE TABLE DONHANGXUAT
(
    MADONHANG VARCHAR(10) NOT NULL,
    MAKH VARCHAR(10),
    MANV VARCHAR(10),
    TRANGTHAIDH  NVARCHAR(30),
    NGAYLAP DATE,
    TONGTIEN MONEY,
    DATHANHTOAN MONEY,
    CONGNO MONEY
    PRIMARY KEY(MADONHANG)
)

CREATE TABLE DONHANGNHAP
(
    MADONHANG VARCHAR(10) NOT NULL,
    MANCC VARCHAR(10),
    TRANGTHAIDH  NVARCHAR(30),
    NGAYLAP DATE,
    TONGTIEN MONEY,
    DATHANHTOAN MONEY,
    CONGNO MONEY
    PRIMARY KEY(MADONHANG)
)

CREATE TABLE NHAPTHUOC
(
    MADONHANG VARCHAR(10) NOT NULL,
    THUOC VARCHAR(10) NOT NULL,
    SOLUONG INT,
    DONVITINH VARCHAR(10),
    THANHTIEN MONEY
    PRIMARY KEY(MADONHANG, THUOC)
)

CREATE TABLE XUATTHUOC
(
    MADONHANG VARCHAR(10) NOT NULL,
    THUOC VARCHAR(10) NOT NULL,
    SOLUONG INT,
    DONVITINH VARCHAR(10),
    THANHTIEN MONEY
    PRIMARY KEY(MADONHANG, THUOC)
)

CREATE TABLE KHOHANG
(
    MATHUOC VARCHAR(10) NOT NULL,
    LANNHAP INT,
    NGAYNHAP DATE,
    NGAYSX DATE,
    NGAYHETHAN DATE,
    SOLUONG INT
    PRIMARY KEY(MATHUOC, LANNHAP)
)

ALTER TABLE THUOC
ADD CONSTRAINT FK_THUOC_NHOMTHUOC FOREIGN KEY(MANHOM)
REFERENCES NHOMTHUOC(MANHOM)
GO

ALTER TABLE THUOC
ADD CONSTRAINT FK_THUOC_NHACC FOREIGN KEY(MANCC)
REFERENCES NHACUNGCAP(MANCC)
GO

ALTER TABLE DONHANGXUAT
ADD CONSTRAINT FK_DONHANGXUAT_KHACHHANG FOREIGN KEY(MAKH)
REFERENCES KHACHHANG(MAKH)
GO

ALTER TABLE DONHANGXUAT
ADD CONSTRAINT FK_DONHANGXUAT_NHANVIEN FOREIGN KEY(MANV)
REFERENCES NHANVIEN(MANV)
GO

ALTER TABLE DONHANGNHAP
ADD CONSTRAINT FK_DONHANGNHAP_NHACUNGCAP FOREIGN KEY(MANCC)
REFERENCES NHACUNGCAP(MANCC)
GO

ALTER TABLE KHOHANG
ADD CONSTRAINT FK_KHOHANG_THUOC FOREIGN KEY(MATHUOC)
REFERENCES THUOC(MATHUOC)
GO

ALTER TABLE XUATTHUOC
ADD CONSTRAINT FK_XUATTHUOC_DONHANGXUAT FOREIGN KEY(MADONHANG)
REFERENCES DONHANGXUAT(MADONHANG)
GO

ALTER TABLE NHAPTHUOC
ADD CONSTRAINT FK_NHAPTHUOC_DONHANGNHAP FOREIGN KEY(MADONHANG)
REFERENCES DONHANGNHAP(MADONHANG)
GO

ALTER TABLE XUATTHUOC
ADD CONSTRAINT FK_XUATTHUOC_THUOC FOREIGN KEY(THUOC)
REFERENCES THUOC(MATHUOC)
GO

ALTER TABLE NHAPTHUOC
ADD CONSTRAINT FK_NHAPTHUOC_THUOC FOREIGN KEY(THUOC)
REFERENCES THUOC(MATHUOC)
GO